# Generated by Django 5.2 on 2025-05-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('document_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('Passaporte', 'Passaporte')], max_length=50)),
                ('document', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=100)),
                ('observations', models.TextField()),
                ('category', models.CharField(choices=[('Alunos', 'Alunos'), ('Professores', 'Professores'), ('Fornecedores', 'Fornecedores/Prestador de serviço')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
