# Generated by Django 5.2 on 2025-05-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_alter_register_adress_alter_register_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
        migrations.AddField(
            model_name='register',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
