# Generated by Django 5.2 on 2025-05-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_remove_register_email_register_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='document',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='observations',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
